<template>
    <div id="Footer">
        <div class="Footer-content">
            Copyright © 2021
        </div>
        <a class="linkDevFast" href="https://devfast.us/">DevFast</a>
    </div>
</template>
<script>
</script>
<style>
    #Footer{
        width: 100%;
        height: 60px;
        background-color: #494E53;
        display: flex;
        justify-content: center;
        align-items: center;
        font-size: 17px;
    }
    .Footer-content{
        width: 150px;
        color: white;
    }
    .linkDevFast{
        color: #007BFF;
        text-decoration: none;
    }

</style>